---
- hosts: testing_server
  become: yes
  tasks:
     - include_vars: users.yml

     - name: Create Groups 
       group: 
          name: admin
          state: present

     - name: Create users
       user:
          name: "{{ item.username }}"
          comment: "{{ item.comment }}"
          password: "{{ item.password }}" 
          shell: /bin/bash
          expires: 1498654800
       with_items: "{{ users }}"

     - name: Add specified users to sudoers file
       lineinfile:
          path: /etc/sudoers
          state: present
          line: "{{ item.username }} ALL=(ALL) NOPASSWD: ALL"
          regexp: "^{{ item.username }}.*"
       when: "{{ item.use_sudo }} == True"
       with_items: "{{ users }}"

